/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoriesTweets extends org.jooq.impl.TableImpl<DBAdapter.tables.records.CategoriesTweetsRecord> {

	private static final long serialVersionUID = -2111934506;

	/**
	 * The singleton instance of <code>MI_WS1314.categories_tweets</code>
	 */
	public static final DBAdapter.tables.CategoriesTweets CATEGORIES_TWEETS = new DBAdapter.tables.CategoriesTweets();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<DBAdapter.tables.records.CategoriesTweetsRecord> getRecordType() {
		return DBAdapter.tables.records.CategoriesTweetsRecord.class;
	}

	/**
	 * The column <code>MI_WS1314.categories_tweets.tweet_id</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.CategoriesTweetsRecord, java.lang.Long> TWEET_ID = createField("tweet_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.categories_tweets.category_id</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.CategoriesTweetsRecord, java.lang.Integer> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>MI_WS1314.categories_tweets</code> table reference
	 */
	public CategoriesTweets() {
		super("categories_tweets", DBAdapter.MiWs1314.MI_WS1314);
	}

	/**
	 * Create an aliased <code>MI_WS1314.categories_tweets</code> table reference
	 */
	public CategoriesTweets(java.lang.String alias) {
		super(alias, DBAdapter.MiWs1314.MI_WS1314, DBAdapter.tables.CategoriesTweets.CATEGORIES_TWEETS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<DBAdapter.tables.records.CategoriesTweetsRecord> getPrimaryKey() {
		return DBAdapter.Keys.KEY_CATEGORIES_TWEETS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<DBAdapter.tables.records.CategoriesTweetsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<DBAdapter.tables.records.CategoriesTweetsRecord>>asList(DBAdapter.Keys.KEY_CATEGORIES_TWEETS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DBAdapter.tables.CategoriesTweets as(java.lang.String alias) {
		return new DBAdapter.tables.CategoriesTweets(alias);
	}
}
