/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoriesTrainingTweets extends org.jooq.impl.TableImpl<DBAdapter.tables.records.CategoriesTrainingTweetsRecord> {

	private static final long serialVersionUID = 369121251;

	/**
	 * The singleton instance of <code>MI_WS1314.categories_training_tweets</code>
	 */
	public static final DBAdapter.tables.CategoriesTrainingTweets CATEGORIES_TRAINING_TWEETS = new DBAdapter.tables.CategoriesTrainingTweets();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<DBAdapter.tables.records.CategoriesTrainingTweetsRecord> getRecordType() {
		return DBAdapter.tables.records.CategoriesTrainingTweetsRecord.class;
	}

	/**
	 * The column <code>MI_WS1314.categories_training_tweets.text</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.CategoriesTrainingTweetsRecord, java.lang.String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR.length(150).nullable(false), this);

	/**
	 * The column <code>MI_WS1314.categories_training_tweets.category</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.CategoriesTrainingTweetsRecord, java.lang.Integer> CATEGORY = createField("category", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>MI_WS1314.categories_training_tweets</code> table reference
	 */
	public CategoriesTrainingTweets() {
		super("categories_training_tweets", DBAdapter.MiWs1314.MI_WS1314);
	}

	/**
	 * Create an aliased <code>MI_WS1314.categories_training_tweets</code> table reference
	 */
	public CategoriesTrainingTweets(java.lang.String alias) {
		super(alias, DBAdapter.MiWs1314.MI_WS1314, DBAdapter.tables.CategoriesTrainingTweets.CATEGORIES_TRAINING_TWEETS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<DBAdapter.tables.records.CategoriesTrainingTweetsRecord> getPrimaryKey() {
		return DBAdapter.Keys.KEY_CATEGORIES_TRAINING_TWEETS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<DBAdapter.tables.records.CategoriesTrainingTweetsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<DBAdapter.tables.records.CategoriesTrainingTweetsRecord>>asList(DBAdapter.Keys.KEY_CATEGORIES_TRAINING_TWEETS_PRIMARY, DBAdapter.Keys.KEY_CATEGORIES_TRAINING_TWEETS_TEXT_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DBAdapter.tables.CategoriesTrainingTweets as(java.lang.String alias) {
		return new DBAdapter.tables.CategoriesTrainingTweets(alias);
	}
}
