/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employees extends org.jooq.impl.TableImpl<DBAdapter.tables.records.EmployeesRecord> {

	private static final long serialVersionUID = 1640382081;

	/**
	 * The singleton instance of <code>MI_WS1314.employees</code>
	 */
	public static final DBAdapter.tables.Employees EMPLOYEES = new DBAdapter.tables.Employees();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<DBAdapter.tables.records.EmployeesRecord> getRecordType() {
		return DBAdapter.tables.records.EmployeesRecord.class;
	}

	/**
	 * The column <code>MI_WS1314.employees.id</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.EmployeesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.employees.first_name</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.EmployeesRecord, java.lang.String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(56), this);

	/**
	 * The column <code>MI_WS1314.employees.last_name</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.EmployeesRecord, java.lang.String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(56), this);

	/**
	 * Create a <code>MI_WS1314.employees</code> table reference
	 */
	public Employees() {
		super("employees", DBAdapter.MiWs1314.MI_WS1314);
	}

	/**
	 * Create an aliased <code>MI_WS1314.employees</code> table reference
	 */
	public Employees(java.lang.String alias) {
		super(alias, DBAdapter.MiWs1314.MI_WS1314, DBAdapter.tables.Employees.EMPLOYEES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<DBAdapter.tables.records.EmployeesRecord, java.lang.Integer> getIdentity() {
		return DBAdapter.Keys.IDENTITY_EMPLOYEES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<DBAdapter.tables.records.EmployeesRecord> getPrimaryKey() {
		return DBAdapter.Keys.KEY_EMPLOYEES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<DBAdapter.tables.records.EmployeesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<DBAdapter.tables.records.EmployeesRecord>>asList(DBAdapter.Keys.KEY_EMPLOYEES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DBAdapter.tables.Employees as(java.lang.String alias) {
		return new DBAdapter.tables.Employees(alias);
	}
}
