/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeodbTypeNames extends org.jooq.impl.TableImpl<DBAdapter.tables.records.GeodbTypeNamesRecord> {

	private static final long serialVersionUID = 640535116;

	/**
	 * The singleton instance of <code>MI_WS1314.geodb_type_names</code>
	 */
	public static final DBAdapter.tables.GeodbTypeNames GEODB_TYPE_NAMES = new DBAdapter.tables.GeodbTypeNames();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<DBAdapter.tables.records.GeodbTypeNamesRecord> getRecordType() {
		return DBAdapter.tables.records.GeodbTypeNamesRecord.class;
	}

	/**
	 * The column <code>MI_WS1314.geodb_type_names.type_id</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbTypeNamesRecord, java.lang.Integer> TYPE_ID = createField("type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_type_names.type_locale</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbTypeNamesRecord, java.lang.String> TYPE_LOCALE = createField("type_locale", org.jooq.impl.SQLDataType.VARCHAR.length(5).nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_type_names.name</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbTypeNamesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * Create a <code>MI_WS1314.geodb_type_names</code> table reference
	 */
	public GeodbTypeNames() {
		super("geodb_type_names", DBAdapter.MiWs1314.MI_WS1314);
	}

	/**
	 * Create an aliased <code>MI_WS1314.geodb_type_names</code> table reference
	 */
	public GeodbTypeNames(java.lang.String alias) {
		super(alias, DBAdapter.MiWs1314.MI_WS1314, DBAdapter.tables.GeodbTypeNames.GEODB_TYPE_NAMES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<DBAdapter.tables.records.GeodbTypeNamesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<DBAdapter.tables.records.GeodbTypeNamesRecord>>asList(DBAdapter.Keys.KEY_GEODB_TYPE_NAMES_TYPE_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DBAdapter.tables.GeodbTypeNames as(java.lang.String alias) {
		return new DBAdapter.tables.GeodbTypeNames(alias);
	}
}
