/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeodbLocations extends org.jooq.impl.TableImpl<DBAdapter.tables.records.GeodbLocationsRecord> {

	private static final long serialVersionUID = 1283235965;

	/**
	 * The singleton instance of <code>MI_WS1314.geodb_locations</code>
	 */
	public static final DBAdapter.tables.GeodbLocations GEODB_LOCATIONS = new DBAdapter.tables.GeodbLocations();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<DBAdapter.tables.records.GeodbLocationsRecord> getRecordType() {
		return DBAdapter.tables.records.GeodbLocationsRecord.class;
	}

	/**
	 * The column <code>MI_WS1314.geodb_locations.loc_id</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbLocationsRecord, java.lang.Integer> LOC_ID = createField("loc_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_locations.loc_type</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbLocationsRecord, java.lang.Integer> LOC_TYPE = createField("loc_type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>MI_WS1314.geodb_locations</code> table reference
	 */
	public GeodbLocations() {
		super("geodb_locations", DBAdapter.MiWs1314.MI_WS1314);
	}

	/**
	 * Create an aliased <code>MI_WS1314.geodb_locations</code> table reference
	 */
	public GeodbLocations(java.lang.String alias) {
		super(alias, DBAdapter.MiWs1314.MI_WS1314, DBAdapter.tables.GeodbLocations.GEODB_LOCATIONS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<DBAdapter.tables.records.GeodbLocationsRecord> getPrimaryKey() {
		return DBAdapter.Keys.KEY_GEODB_LOCATIONS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<DBAdapter.tables.records.GeodbLocationsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<DBAdapter.tables.records.GeodbLocationsRecord>>asList(DBAdapter.Keys.KEY_GEODB_LOCATIONS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DBAdapter.tables.GeodbLocations as(java.lang.String alias) {
		return new DBAdapter.tables.GeodbLocations(alias);
	}
}
