/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeodbHierarchies extends org.jooq.impl.TableImpl<DBAdapter.tables.records.GeodbHierarchiesRecord> {

	private static final long serialVersionUID = -587971774;

	/**
	 * The singleton instance of <code>MI_WS1314.geodb_hierarchies</code>
	 */
	public static final DBAdapter.tables.GeodbHierarchies GEODB_HIERARCHIES = new DBAdapter.tables.GeodbHierarchies();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<DBAdapter.tables.records.GeodbHierarchiesRecord> getRecordType() {
		return DBAdapter.tables.records.GeodbHierarchiesRecord.class;
	}

	/**
	 * The column <code>MI_WS1314.geodb_hierarchies.loc_id</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbHierarchiesRecord, java.lang.Integer> LOC_ID = createField("loc_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_hierarchies.level</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbHierarchiesRecord, java.lang.Integer> LEVEL = createField("level", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_hierarchies.id_lvl1</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbHierarchiesRecord, java.lang.Integer> ID_LVL1 = createField("id_lvl1", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_hierarchies.id_lvl2</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbHierarchiesRecord, java.lang.Integer> ID_LVL2 = createField("id_lvl2", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.geodb_hierarchies.id_lvl3</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbHierarchiesRecord, java.lang.Integer> ID_LVL3 = createField("id_lvl3", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.geodb_hierarchies.id_lvl4</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbHierarchiesRecord, java.lang.Integer> ID_LVL4 = createField("id_lvl4", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.geodb_hierarchies.id_lvl5</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbHierarchiesRecord, java.lang.Integer> ID_LVL5 = createField("id_lvl5", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.geodb_hierarchies.id_lvl6</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbHierarchiesRecord, java.lang.Integer> ID_LVL6 = createField("id_lvl6", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.geodb_hierarchies.id_lvl7</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbHierarchiesRecord, java.lang.Integer> ID_LVL7 = createField("id_lvl7", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.geodb_hierarchies.id_lvl8</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbHierarchiesRecord, java.lang.Integer> ID_LVL8 = createField("id_lvl8", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.geodb_hierarchies.id_lvl9</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbHierarchiesRecord, java.lang.Integer> ID_LVL9 = createField("id_lvl9", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.geodb_hierarchies.valid_since</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbHierarchiesRecord, java.sql.Date> VALID_SINCE = createField("valid_since", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * The column <code>MI_WS1314.geodb_hierarchies.date_type_since</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbHierarchiesRecord, java.lang.Integer> DATE_TYPE_SINCE = createField("date_type_since", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.geodb_hierarchies.valid_until</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbHierarchiesRecord, java.sql.Date> VALID_UNTIL = createField("valid_until", org.jooq.impl.SQLDataType.DATE.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_hierarchies.date_type_until</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbHierarchiesRecord, java.lang.Integer> DATE_TYPE_UNTIL = createField("date_type_until", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>MI_WS1314.geodb_hierarchies</code> table reference
	 */
	public GeodbHierarchies() {
		super("geodb_hierarchies", DBAdapter.MiWs1314.MI_WS1314);
	}

	/**
	 * Create an aliased <code>MI_WS1314.geodb_hierarchies</code> table reference
	 */
	public GeodbHierarchies(java.lang.String alias) {
		super(alias, DBAdapter.MiWs1314.MI_WS1314, DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DBAdapter.tables.GeodbHierarchies as(java.lang.String alias) {
		return new DBAdapter.tables.GeodbHierarchies(alias);
	}
}
