/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeodbIntdata extends org.jooq.impl.TableImpl<DBAdapter.tables.records.GeodbIntdataRecord> {

	private static final long serialVersionUID = -605382695;

	/**
	 * The singleton instance of <code>MI_WS1314.geodb_intdata</code>
	 */
	public static final DBAdapter.tables.GeodbIntdata GEODB_INTDATA = new DBAdapter.tables.GeodbIntdata();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<DBAdapter.tables.records.GeodbIntdataRecord> getRecordType() {
		return DBAdapter.tables.records.GeodbIntdataRecord.class;
	}

	/**
	 * The column <code>MI_WS1314.geodb_intdata.loc_id</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbIntdataRecord, java.lang.Integer> LOC_ID = createField("loc_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_intdata.int_type</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbIntdataRecord, java.lang.Integer> INT_TYPE = createField("int_type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_intdata.int_val</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbIntdataRecord, java.lang.Long> INT_VAL = createField("int_val", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_intdata.valid_since</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbIntdataRecord, java.sql.Date> VALID_SINCE = createField("valid_since", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * The column <code>MI_WS1314.geodb_intdata.date_type_since</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbIntdataRecord, java.lang.Integer> DATE_TYPE_SINCE = createField("date_type_since", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.geodb_intdata.valid_until</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbIntdataRecord, java.sql.Date> VALID_UNTIL = createField("valid_until", org.jooq.impl.SQLDataType.DATE.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_intdata.date_type_until</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbIntdataRecord, java.lang.Integer> DATE_TYPE_UNTIL = createField("date_type_until", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>MI_WS1314.geodb_intdata</code> table reference
	 */
	public GeodbIntdata() {
		super("geodb_intdata", DBAdapter.MiWs1314.MI_WS1314);
	}

	/**
	 * Create an aliased <code>MI_WS1314.geodb_intdata</code> table reference
	 */
	public GeodbIntdata(java.lang.String alias) {
		super(alias, DBAdapter.MiWs1314.MI_WS1314, DBAdapter.tables.GeodbIntdata.GEODB_INTDATA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DBAdapter.tables.GeodbIntdata as(java.lang.String alias) {
		return new DBAdapter.tables.GeodbIntdata(alias);
	}
}
