/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeodbFloatdata extends org.jooq.impl.TableImpl<DBAdapter.tables.records.GeodbFloatdataRecord> {

	private static final long serialVersionUID = 687984767;

	/**
	 * The singleton instance of <code>MI_WS1314.geodb_floatdata</code>
	 */
	public static final DBAdapter.tables.GeodbFloatdata GEODB_FLOATDATA = new DBAdapter.tables.GeodbFloatdata();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<DBAdapter.tables.records.GeodbFloatdataRecord> getRecordType() {
		return DBAdapter.tables.records.GeodbFloatdataRecord.class;
	}

	/**
	 * The column <code>MI_WS1314.geodb_floatdata.loc_id</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbFloatdataRecord, java.lang.Integer> LOC_ID = createField("loc_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_floatdata.float_type</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbFloatdataRecord, java.lang.Integer> FLOAT_TYPE = createField("float_type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_floatdata.float_val</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbFloatdataRecord, java.lang.Double> FLOAT_VAL = createField("float_val", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_floatdata.valid_since</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbFloatdataRecord, java.sql.Date> VALID_SINCE = createField("valid_since", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * The column <code>MI_WS1314.geodb_floatdata.date_type_since</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbFloatdataRecord, java.lang.Integer> DATE_TYPE_SINCE = createField("date_type_since", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.geodb_floatdata.valid_until</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbFloatdataRecord, java.sql.Date> VALID_UNTIL = createField("valid_until", org.jooq.impl.SQLDataType.DATE.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_floatdata.date_type_until</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbFloatdataRecord, java.lang.Integer> DATE_TYPE_UNTIL = createField("date_type_until", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>MI_WS1314.geodb_floatdata</code> table reference
	 */
	public GeodbFloatdata() {
		super("geodb_floatdata", DBAdapter.MiWs1314.MI_WS1314);
	}

	/**
	 * Create an aliased <code>MI_WS1314.geodb_floatdata</code> table reference
	 */
	public GeodbFloatdata(java.lang.String alias) {
		super(alias, DBAdapter.MiWs1314.MI_WS1314, DBAdapter.tables.GeodbFloatdata.GEODB_FLOATDATA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DBAdapter.tables.GeodbFloatdata as(java.lang.String alias) {
		return new DBAdapter.tables.GeodbFloatdata(alias);
	}
}
