/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeodbChangelog extends org.jooq.impl.TableImpl<DBAdapter.tables.records.GeodbChangelogRecord> {

	private static final long serialVersionUID = 535424675;

	/**
	 * The singleton instance of <code>MI_WS1314.geodb_changelog</code>
	 */
	public static final DBAdapter.tables.GeodbChangelog GEODB_CHANGELOG = new DBAdapter.tables.GeodbChangelog();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<DBAdapter.tables.records.GeodbChangelogRecord> getRecordType() {
		return DBAdapter.tables.records.GeodbChangelogRecord.class;
	}

	/**
	 * The column <code>MI_WS1314.geodb_changelog.id</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbChangelogRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_changelog.datum</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbChangelogRecord, java.sql.Date> DATUM = createField("datum", org.jooq.impl.SQLDataType.DATE.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_changelog.beschreibung</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbChangelogRecord, java.lang.String> BESCHREIBUNG = createField("beschreibung", org.jooq.impl.SQLDataType.CLOB.length(65535).nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_changelog.autor</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbChangelogRecord, java.lang.String> AUTOR = createField("autor", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_changelog.version</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbChangelogRecord, java.lang.String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR.length(8), this);

	/**
	 * Create a <code>MI_WS1314.geodb_changelog</code> table reference
	 */
	public GeodbChangelog() {
		super("geodb_changelog", DBAdapter.MiWs1314.MI_WS1314);
	}

	/**
	 * Create an aliased <code>MI_WS1314.geodb_changelog</code> table reference
	 */
	public GeodbChangelog(java.lang.String alias) {
		super(alias, DBAdapter.MiWs1314.MI_WS1314, DBAdapter.tables.GeodbChangelog.GEODB_CHANGELOG);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<DBAdapter.tables.records.GeodbChangelogRecord> getPrimaryKey() {
		return DBAdapter.Keys.KEY_GEODB_CHANGELOG_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<DBAdapter.tables.records.GeodbChangelogRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<DBAdapter.tables.records.GeodbChangelogRecord>>asList(DBAdapter.Keys.KEY_GEODB_CHANGELOG_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DBAdapter.tables.GeodbChangelog as(java.lang.String alias) {
		return new DBAdapter.tables.GeodbChangelog(alias);
	}
}
