/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeodbTextdata extends org.jooq.impl.TableImpl<DBAdapter.tables.records.GeodbTextdataRecord> {

	private static final long serialVersionUID = 976627588;

	/**
	 * The singleton instance of <code>MI_WS1314.geodb_textdata</code>
	 */
	public static final DBAdapter.tables.GeodbTextdata GEODB_TEXTDATA = new DBAdapter.tables.GeodbTextdata();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<DBAdapter.tables.records.GeodbTextdataRecord> getRecordType() {
		return DBAdapter.tables.records.GeodbTextdataRecord.class;
	}

	/**
	 * The column <code>MI_WS1314.geodb_textdata.loc_id</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbTextdataRecord, java.lang.Integer> LOC_ID = createField("loc_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_textdata.text_type</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbTextdataRecord, java.lang.Integer> TEXT_TYPE = createField("text_type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_textdata.text_val</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbTextdataRecord, java.lang.String> TEXT_VAL = createField("text_val", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_textdata.text_locale</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbTextdataRecord, java.lang.String> TEXT_LOCALE = createField("text_locale", org.jooq.impl.SQLDataType.VARCHAR.length(5), this);

	/**
	 * The column <code>MI_WS1314.geodb_textdata.is_native_lang</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbTextdataRecord, java.lang.Short> IS_NATIVE_LANG = createField("is_native_lang", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * The column <code>MI_WS1314.geodb_textdata.is_default_name</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbTextdataRecord, java.lang.Short> IS_DEFAULT_NAME = createField("is_default_name", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * The column <code>MI_WS1314.geodb_textdata.valid_since</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbTextdataRecord, java.sql.Date> VALID_SINCE = createField("valid_since", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * The column <code>MI_WS1314.geodb_textdata.date_type_since</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbTextdataRecord, java.lang.Integer> DATE_TYPE_SINCE = createField("date_type_since", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.geodb_textdata.valid_until</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbTextdataRecord, java.sql.Date> VALID_UNTIL = createField("valid_until", org.jooq.impl.SQLDataType.DATE.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_textdata.date_type_until</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbTextdataRecord, java.lang.Integer> DATE_TYPE_UNTIL = createField("date_type_until", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>MI_WS1314.geodb_textdata</code> table reference
	 */
	public GeodbTextdata() {
		super("geodb_textdata", DBAdapter.MiWs1314.MI_WS1314);
	}

	/**
	 * Create an aliased <code>MI_WS1314.geodb_textdata</code> table reference
	 */
	public GeodbTextdata(java.lang.String alias) {
		super(alias, DBAdapter.MiWs1314.MI_WS1314, DBAdapter.tables.GeodbTextdata.GEODB_TEXTDATA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DBAdapter.tables.GeodbTextdata as(java.lang.String alias) {
		return new DBAdapter.tables.GeodbTextdata(alias);
	}
}
