/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeodbCoordinates extends org.jooq.impl.TableImpl<DBAdapter.tables.records.GeodbCoordinatesRecord> {

	private static final long serialVersionUID = -851193450;

	/**
	 * The singleton instance of <code>MI_WS1314.geodb_coordinates</code>
	 */
	public static final DBAdapter.tables.GeodbCoordinates GEODB_COORDINATES = new DBAdapter.tables.GeodbCoordinates();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<DBAdapter.tables.records.GeodbCoordinatesRecord> getRecordType() {
		return DBAdapter.tables.records.GeodbCoordinatesRecord.class;
	}

	/**
	 * The column <code>MI_WS1314.geodb_coordinates.loc_id</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbCoordinatesRecord, java.lang.Integer> LOC_ID = createField("loc_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_coordinates.coord_type</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbCoordinatesRecord, java.lang.Integer> COORD_TYPE = createField("coord_type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_coordinates.lat</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbCoordinatesRecord, java.lang.Double> LAT = createField("lat", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>MI_WS1314.geodb_coordinates.lon</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbCoordinatesRecord, java.lang.Double> LON = createField("lon", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>MI_WS1314.geodb_coordinates.coord_subtype</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbCoordinatesRecord, java.lang.Integer> COORD_SUBTYPE = createField("coord_subtype", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.geodb_coordinates.valid_since</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbCoordinatesRecord, java.sql.Date> VALID_SINCE = createField("valid_since", org.jooq.impl.SQLDataType.DATE, this);

	/**
	 * The column <code>MI_WS1314.geodb_coordinates.date_type_since</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbCoordinatesRecord, java.lang.Integer> DATE_TYPE_SINCE = createField("date_type_since", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.geodb_coordinates.valid_until</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbCoordinatesRecord, java.sql.Date> VALID_UNTIL = createField("valid_until", org.jooq.impl.SQLDataType.DATE.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.geodb_coordinates.date_type_until</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.GeodbCoordinatesRecord, java.lang.Integer> DATE_TYPE_UNTIL = createField("date_type_until", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>MI_WS1314.geodb_coordinates</code> table reference
	 */
	public GeodbCoordinates() {
		super("geodb_coordinates", DBAdapter.MiWs1314.MI_WS1314);
	}

	/**
	 * Create an aliased <code>MI_WS1314.geodb_coordinates</code> table reference
	 */
	public GeodbCoordinates(java.lang.String alias) {
		super(alias, DBAdapter.MiWs1314.MI_WS1314, DBAdapter.tables.GeodbCoordinates.GEODB_COORDINATES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DBAdapter.tables.GeodbCoordinates as(java.lang.String alias) {
		return new DBAdapter.tables.GeodbCoordinates(alias);
	}
}
