/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tags extends org.jooq.impl.TableImpl<DBAdapter.tables.records.TagsRecord> {

	private static final long serialVersionUID = 1744789429;

	/**
	 * The singleton instance of <code>MI_WS1314.tags</code>
	 */
	public static final DBAdapter.tables.Tags TAGS = new DBAdapter.tables.Tags();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<DBAdapter.tables.records.TagsRecord> getRecordType() {
		return DBAdapter.tables.records.TagsRecord.class;
	}

	/**
	 * The column <code>MI_WS1314.tags.id</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TagsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.tags.name</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TagsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(200), this);

	/**
	 * Create a <code>MI_WS1314.tags</code> table reference
	 */
	public Tags() {
		super("tags", DBAdapter.MiWs1314.MI_WS1314);
	}

	/**
	 * Create an aliased <code>MI_WS1314.tags</code> table reference
	 */
	public Tags(java.lang.String alias) {
		super(alias, DBAdapter.MiWs1314.MI_WS1314, DBAdapter.tables.Tags.TAGS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<DBAdapter.tables.records.TagsRecord, java.lang.Integer> getIdentity() {
		return DBAdapter.Keys.IDENTITY_TAGS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<DBAdapter.tables.records.TagsRecord> getPrimaryKey() {
		return DBAdapter.Keys.KEY_TAGS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<DBAdapter.tables.records.TagsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<DBAdapter.tables.records.TagsRecord>>asList(DBAdapter.Keys.KEY_TAGS_PRIMARY, DBAdapter.Keys.KEY_TAGS_INDEX_TAGS_ON_NAME);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DBAdapter.tables.Tags as(java.lang.String alias) {
		return new DBAdapter.tables.Tags(alias);
	}
}
