/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagsTweets extends org.jooq.impl.TableImpl<DBAdapter.tables.records.TagsTweetsRecord> {

	private static final long serialVersionUID = 1951602858;

	/**
	 * The singleton instance of <code>MI_WS1314.tags_tweets</code>
	 */
	public static final DBAdapter.tables.TagsTweets TAGS_TWEETS = new DBAdapter.tables.TagsTweets();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<DBAdapter.tables.records.TagsTweetsRecord> getRecordType() {
		return DBAdapter.tables.records.TagsTweetsRecord.class;
	}

	/**
	 * The column <code>MI_WS1314.tags_tweets.tweet_id</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TagsTweetsRecord, java.lang.Long> TWEET_ID = createField("tweet_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.tags_tweets.tag_id</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TagsTweetsRecord, java.lang.Integer> TAG_ID = createField("tag_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>MI_WS1314.tags_tweets</code> table reference
	 */
	public TagsTweets() {
		super("tags_tweets", DBAdapter.MiWs1314.MI_WS1314);
	}

	/**
	 * Create an aliased <code>MI_WS1314.tags_tweets</code> table reference
	 */
	public TagsTweets(java.lang.String alias) {
		super(alias, DBAdapter.MiWs1314.MI_WS1314, DBAdapter.tables.TagsTweets.TAGS_TWEETS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<DBAdapter.tables.records.TagsTweetsRecord> getPrimaryKey() {
		return DBAdapter.Keys.KEY_TAGS_TWEETS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<DBAdapter.tables.records.TagsTweetsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<DBAdapter.tables.records.TagsTweetsRecord>>asList(DBAdapter.Keys.KEY_TAGS_TWEETS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DBAdapter.tables.TagsTweets as(java.lang.String alias) {
		return new DBAdapter.tables.TagsTweets(alias);
	}
}
