/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TweetsSyria extends org.jooq.impl.TableImpl<DBAdapter.tables.records.TweetsSyriaRecord> {

	private static final long serialVersionUID = 798486894;

	/**
	 * The singleton instance of <code>MI_WS1314.tweets_syria</code>
	 */
	public static final DBAdapter.tables.TweetsSyria TWEETS_SYRIA = new DBAdapter.tables.TweetsSyria();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<DBAdapter.tables.records.TweetsSyriaRecord> getRecordType() {
		return DBAdapter.tables.records.TweetsSyriaRecord.class;
	}

	/**
	 * The column <code>MI_WS1314.tweets_syria.id</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsSyriaRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.tweets_syria.iteration</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsSyriaRecord, java.lang.Integer> ITERATION = createField("iteration", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.tweets_syria.text</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsSyriaRecord, java.lang.String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR.length(150), this);

	/**
	 * The column <code>MI_WS1314.tweets_syria.hashtags</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsSyriaRecord, java.lang.String> HASHTAGS = createField("hashtags", org.jooq.impl.SQLDataType.VARCHAR.length(150), this);

	/**
	 * The column <code>MI_WS1314.tweets_syria.author</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsSyriaRecord, java.lang.String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>MI_WS1314.tweets_syria.retweets</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsSyriaRecord, java.lang.Integer> RETWEETS = createField("retweets", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.tweets_syria.timestamp</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsSyriaRecord, java.sql.Timestamp> TIMESTAMP = createField("timestamp", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>MI_WS1314.tweets_syria.follower</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsSyriaRecord, java.lang.Integer> FOLLOWER = createField("follower", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.tweets_syria.geolocation</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsSyriaRecord, java.lang.String> GEOLOCATION = createField("geolocation", org.jooq.impl.SQLDataType.VARCHAR.length(200), this);

	/**
	 * The column <code>MI_WS1314.tweets_syria.place</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsSyriaRecord, java.lang.String> PLACE = createField("place", org.jooq.impl.SQLDataType.VARCHAR.length(200), this);

	/**
	 * The column <code>MI_WS1314.tweets_syria.commentRef</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsSyriaRecord, java.lang.Long> COMMENTREF = createField("commentRef", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>MI_WS1314.tweets_syria</code> table reference
	 */
	public TweetsSyria() {
		super("tweets_syria", DBAdapter.MiWs1314.MI_WS1314);
	}

	/**
	 * Create an aliased <code>MI_WS1314.tweets_syria</code> table reference
	 */
	public TweetsSyria(java.lang.String alias) {
		super(alias, DBAdapter.MiWs1314.MI_WS1314, DBAdapter.tables.TweetsSyria.TWEETS_SYRIA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<DBAdapter.tables.records.TweetsSyriaRecord> getPrimaryKey() {
		return DBAdapter.Keys.KEY_TWEETS_SYRIA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<DBAdapter.tables.records.TweetsSyriaRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<DBAdapter.tables.records.TweetsSyriaRecord>>asList(DBAdapter.Keys.KEY_TWEETS_SYRIA_PRIMARY, DBAdapter.Keys.KEY_TWEETS_SYRIA_ID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DBAdapter.tables.TweetsSyria as(java.lang.String alias) {
		return new DBAdapter.tables.TweetsSyria(alias);
	}
}
