/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TweetsHochwasser extends org.jooq.impl.TableImpl<DBAdapter.tables.records.TweetsHochwasserRecord> {

	private static final long serialVersionUID = -1805704053;

	/**
	 * The singleton instance of <code>MI_WS1314.tweets_hochwasser</code>
	 */
	public static final DBAdapter.tables.TweetsHochwasser TWEETS_HOCHWASSER = new DBAdapter.tables.TweetsHochwasser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<DBAdapter.tables.records.TweetsHochwasserRecord> getRecordType() {
		return DBAdapter.tables.records.TweetsHochwasserRecord.class;
	}

	/**
	 * The column <code>MI_WS1314.tweets_hochwasser.id</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsHochwasserRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this);

	/**
	 * The column <code>MI_WS1314.tweets_hochwasser.iteration</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsHochwasserRecord, java.lang.Integer> ITERATION = createField("iteration", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.tweets_hochwasser.text</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsHochwasserRecord, java.lang.String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR.length(500), this);

	/**
	 * The column <code>MI_WS1314.tweets_hochwasser.hashtags</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsHochwasserRecord, java.lang.String> HASHTAGS = createField("hashtags", org.jooq.impl.SQLDataType.VARCHAR.length(150), this);

	/**
	 * The column <code>MI_WS1314.tweets_hochwasser.author</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsHochwasserRecord, java.lang.String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.VARCHAR.length(50), this);

	/**
	 * The column <code>MI_WS1314.tweets_hochwasser.retweets</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsHochwasserRecord, java.lang.Integer> RETWEETS = createField("retweets", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.tweets_hochwasser.timestamp</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsHochwasserRecord, java.sql.Timestamp> TIMESTAMP = createField("timestamp", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>MI_WS1314.tweets_hochwasser.follower</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsHochwasserRecord, java.lang.Integer> FOLLOWER = createField("follower", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>MI_WS1314.tweets_hochwasser.geolocation</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsHochwasserRecord, java.lang.String> GEOLOCATION = createField("geolocation", org.jooq.impl.SQLDataType.VARCHAR.length(200), this);

	/**
	 * The column <code>MI_WS1314.tweets_hochwasser.place</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsHochwasserRecord, java.lang.String> PLACE = createField("place", org.jooq.impl.SQLDataType.VARCHAR.length(200), this);

	/**
	 * The column <code>MI_WS1314.tweets_hochwasser.commentRef</code>. 
	 */
	public final org.jooq.TableField<DBAdapter.tables.records.TweetsHochwasserRecord, java.lang.Long> COMMENTREF = createField("commentRef", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>MI_WS1314.tweets_hochwasser</code> table reference
	 */
	public TweetsHochwasser() {
		super("tweets_hochwasser", DBAdapter.MiWs1314.MI_WS1314);
	}

	/**
	 * Create an aliased <code>MI_WS1314.tweets_hochwasser</code> table reference
	 */
	public TweetsHochwasser(java.lang.String alias) {
		super(alias, DBAdapter.MiWs1314.MI_WS1314, DBAdapter.tables.TweetsHochwasser.TWEETS_HOCHWASSER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<DBAdapter.tables.records.TweetsHochwasserRecord, java.lang.Long> getIdentity() {
		return DBAdapter.Keys.IDENTITY_TWEETS_HOCHWASSER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<DBAdapter.tables.records.TweetsHochwasserRecord> getPrimaryKey() {
		return DBAdapter.Keys.KEY_TWEETS_HOCHWASSER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<DBAdapter.tables.records.TweetsHochwasserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<DBAdapter.tables.records.TweetsHochwasserRecord>>asList(DBAdapter.Keys.KEY_TWEETS_HOCHWASSER_PRIMARY, DBAdapter.Keys.KEY_TWEETS_HOCHWASSER_ID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DBAdapter.tables.TweetsHochwasser as(java.lang.String alias) {
		return new DBAdapter.tables.TweetsHochwasser(alias);
	}
}
