/**
 * This class is generated by jOOQ
 */
package DBAdapter;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in MI_WS1314
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table MI_WS1314.categories
	 */
	public static final DBAdapter.tables.Categories CATEGORIES = DBAdapter.tables.Categories.CATEGORIES;

	/**
	 * The table MI_WS1314.categories_training_tweets
	 */
	public static final DBAdapter.tables.CategoriesTrainingTweets CATEGORIES_TRAINING_TWEETS = DBAdapter.tables.CategoriesTrainingTweets.CATEGORIES_TRAINING_TWEETS;

	/**
	 * The table MI_WS1314.categories_tweets
	 */
	public static final DBAdapter.tables.CategoriesTweets CATEGORIES_TWEETS = DBAdapter.tables.CategoriesTweets.CATEGORIES_TWEETS;

	/**
	 * The table MI_WS1314.employees
	 */
	public static final DBAdapter.tables.Employees EMPLOYEES = DBAdapter.tables.Employees.EMPLOYEES;

	/**
	 * The table MI_WS1314.geodb_changelog
	 */
	public static final DBAdapter.tables.GeodbChangelog GEODB_CHANGELOG = DBAdapter.tables.GeodbChangelog.GEODB_CHANGELOG;

	/**
	 * The table MI_WS1314.geodb_coordinates
	 */
	public static final DBAdapter.tables.GeodbCoordinates GEODB_COORDINATES = DBAdapter.tables.GeodbCoordinates.GEODB_COORDINATES;

	/**
	 * The table MI_WS1314.geodb_floatdata
	 */
	public static final DBAdapter.tables.GeodbFloatdata GEODB_FLOATDATA = DBAdapter.tables.GeodbFloatdata.GEODB_FLOATDATA;

	/**
	 * The table MI_WS1314.geodb_hierarchies
	 */
	public static final DBAdapter.tables.GeodbHierarchies GEODB_HIERARCHIES = DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES;

	/**
	 * The table MI_WS1314.geodb_intdata
	 */
	public static final DBAdapter.tables.GeodbIntdata GEODB_INTDATA = DBAdapter.tables.GeodbIntdata.GEODB_INTDATA;

	/**
	 * The table MI_WS1314.geodb_locations
	 */
	public static final DBAdapter.tables.GeodbLocations GEODB_LOCATIONS = DBAdapter.tables.GeodbLocations.GEODB_LOCATIONS;

	/**
	 * The table MI_WS1314.geodb_textdata
	 */
	public static final DBAdapter.tables.GeodbTextdata GEODB_TEXTDATA = DBAdapter.tables.GeodbTextdata.GEODB_TEXTDATA;

	/**
	 * The table MI_WS1314.geodb_type_names
	 */
	public static final DBAdapter.tables.GeodbTypeNames GEODB_TYPE_NAMES = DBAdapter.tables.GeodbTypeNames.GEODB_TYPE_NAMES;

	/**
	 * The table MI_WS1314.information
	 */
	public static final DBAdapter.tables.Information INFORMATION = DBAdapter.tables.Information.INFORMATION;

	/**
	 * The table MI_WS1314.tags
	 */
	public static final DBAdapter.tables.Tags TAGS = DBAdapter.tables.Tags.TAGS;

	/**
	 * The table MI_WS1314.tags_tweets
	 */
	public static final DBAdapter.tables.TagsTweets TAGS_TWEETS = DBAdapter.tables.TagsTweets.TAGS_TWEETS;

	/**
	 * The table MI_WS1314.tweets_hochwasser
	 */
	public static final DBAdapter.tables.TweetsHochwasser TWEETS_HOCHWASSER = DBAdapter.tables.TweetsHochwasser.TWEETS_HOCHWASSER;

	/**
	 * The table MI_WS1314.tweets_sturm
	 */
	public static final DBAdapter.tables.TweetsSturm TWEETS_STURM = DBAdapter.tables.TweetsSturm.TWEETS_STURM;

	/**
	 * The table MI_WS1314.tweets_syria
	 */
	public static final DBAdapter.tables.TweetsSyria TWEETS_SYRIA = DBAdapter.tables.TweetsSyria.TWEETS_SYRIA;
}
