source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

gem 'sinatra', '>= 1.3.0', :require => nil
gem 'sidekiq'
gem 'clockwork'

gem 'sqlite3'
gem 'mysql2'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'haml-rails'

# JavaScript templating
gem 'haml_coffee_assets'
gem 'execjs'

gem 'composite_primary_keys'

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem "leaflet-rails", "~> 0.6.4"

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :development do
  gem 'zeus'
  gem 'thin'
  gem 'better_errors'
  gem 'binding_of_caller' # For better_errors
end

# Use ActiveModel has_secure_password
gem 'bcrypt-ruby', '~> 3.0.0'

gem 'websocket-rails'

