/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoriesTweetsRecord extends org.jooq.impl.UpdatableRecordImpl<DBAdapter.tables.records.CategoriesTweetsRecord> implements org.jooq.Record2<java.lang.Long, java.lang.Integer> {

	private static final long serialVersionUID = -191339487;

	/**
	 * Setter for <code>MI_WS1314.categories_tweets.tweet_id</code>. 
	 */
	public void setTweetId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>MI_WS1314.categories_tweets.tweet_id</code>. 
	 */
	public java.lang.Long getTweetId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>MI_WS1314.categories_tweets.category_id</code>. 
	 */
	public void setCategoryId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>MI_WS1314.categories_tweets.category_id</code>. 
	 */
	public java.lang.Integer getCategoryId() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Integer, java.lang.Long> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return DBAdapter.tables.CategoriesTweets.CATEGORIES_TWEETS.TWEET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return DBAdapter.tables.CategoriesTweets.CATEGORIES_TWEETS.CATEGORY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getTweetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getCategoryId();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CategoriesTweetsRecord
	 */
	public CategoriesTweetsRecord() {
		super(DBAdapter.tables.CategoriesTweets.CATEGORIES_TWEETS);
	}

	/**
	 * Create a detached, initialised CategoriesTweetsRecord
	 */
	public CategoriesTweetsRecord(java.lang.Long tweetId, java.lang.Integer categoryId) {
		super(DBAdapter.tables.CategoriesTweets.CATEGORIES_TWEETS);

		setValue(0, tweetId);
		setValue(1, categoryId);
	}
}
