/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoriesTrainingTweetsRecord extends org.jooq.impl.UpdatableRecordImpl<DBAdapter.tables.records.CategoriesTrainingTweetsRecord> implements org.jooq.Record2<java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -1812340073;

	/**
	 * Setter for <code>MI_WS1314.categories_training_tweets.text</code>. 
	 */
	public void setText(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>MI_WS1314.categories_training_tweets.text</code>. 
	 */
	public java.lang.String getText() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>MI_WS1314.categories_training_tweets.category</code>. 
	 */
	public void setCategory(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>MI_WS1314.categories_training_tweets.category</code>. 
	 */
	public java.lang.Integer getCategory() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return DBAdapter.tables.CategoriesTrainingTweets.CATEGORIES_TRAINING_TWEETS.TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return DBAdapter.tables.CategoriesTrainingTweets.CATEGORIES_TRAINING_TWEETS.CATEGORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getCategory();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CategoriesTrainingTweetsRecord
	 */
	public CategoriesTrainingTweetsRecord() {
		super(DBAdapter.tables.CategoriesTrainingTweets.CATEGORIES_TRAINING_TWEETS);
	}

	/**
	 * Create a detached, initialised CategoriesTrainingTweetsRecord
	 */
	public CategoriesTrainingTweetsRecord(java.lang.String text, java.lang.Integer category) {
		super(DBAdapter.tables.CategoriesTrainingTweets.CATEGORIES_TRAINING_TWEETS);

		setValue(0, text);
		setValue(1, category);
	}
}
