/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeodbHierarchiesRecord extends org.jooq.impl.TableRecordImpl<DBAdapter.tables.records.GeodbHierarchiesRecord> implements org.jooq.Record15<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Date, java.lang.Integer, java.sql.Date, java.lang.Integer> {

	private static final long serialVersionUID = 528667499;

	/**
	 * Setter for <code>MI_WS1314.geodb_hierarchies.loc_id</code>. 
	 */
	public void setLocId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_hierarchies.loc_id</code>. 
	 */
	public java.lang.Integer getLocId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_hierarchies.level</code>. 
	 */
	public void setLevel(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_hierarchies.level</code>. 
	 */
	public java.lang.Integer getLevel() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_hierarchies.id_lvl1</code>. 
	 */
	public void setIdLvl1(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_hierarchies.id_lvl1</code>. 
	 */
	public java.lang.Integer getIdLvl1() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_hierarchies.id_lvl2</code>. 
	 */
	public void setIdLvl2(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_hierarchies.id_lvl2</code>. 
	 */
	public java.lang.Integer getIdLvl2() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_hierarchies.id_lvl3</code>. 
	 */
	public void setIdLvl3(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_hierarchies.id_lvl3</code>. 
	 */
	public java.lang.Integer getIdLvl3() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_hierarchies.id_lvl4</code>. 
	 */
	public void setIdLvl4(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_hierarchies.id_lvl4</code>. 
	 */
	public java.lang.Integer getIdLvl4() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_hierarchies.id_lvl5</code>. 
	 */
	public void setIdLvl5(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_hierarchies.id_lvl5</code>. 
	 */
	public java.lang.Integer getIdLvl5() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_hierarchies.id_lvl6</code>. 
	 */
	public void setIdLvl6(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_hierarchies.id_lvl6</code>. 
	 */
	public java.lang.Integer getIdLvl6() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_hierarchies.id_lvl7</code>. 
	 */
	public void setIdLvl7(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_hierarchies.id_lvl7</code>. 
	 */
	public java.lang.Integer getIdLvl7() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_hierarchies.id_lvl8</code>. 
	 */
	public void setIdLvl8(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_hierarchies.id_lvl8</code>. 
	 */
	public java.lang.Integer getIdLvl8() {
		return (java.lang.Integer) getValue(9);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_hierarchies.id_lvl9</code>. 
	 */
	public void setIdLvl9(java.lang.Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_hierarchies.id_lvl9</code>. 
	 */
	public java.lang.Integer getIdLvl9() {
		return (java.lang.Integer) getValue(10);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_hierarchies.valid_since</code>. 
	 */
	public void setValidSince(java.sql.Date value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_hierarchies.valid_since</code>. 
	 */
	public java.sql.Date getValidSince() {
		return (java.sql.Date) getValue(11);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_hierarchies.date_type_since</code>. 
	 */
	public void setDateTypeSince(java.lang.Integer value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_hierarchies.date_type_since</code>. 
	 */
	public java.lang.Integer getDateTypeSince() {
		return (java.lang.Integer) getValue(12);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_hierarchies.valid_until</code>. 
	 */
	public void setValidUntil(java.sql.Date value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_hierarchies.valid_until</code>. 
	 */
	public java.sql.Date getValidUntil() {
		return (java.sql.Date) getValue(13);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_hierarchies.date_type_until</code>. 
	 */
	public void setDateTypeUntil(java.lang.Integer value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_hierarchies.date_type_until</code>. 
	 */
	public java.lang.Integer getDateTypeUntil() {
		return (java.lang.Integer) getValue(14);
	}

	// -------------------------------------------------------------------------
	// Record15 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row15<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Date, java.lang.Integer, java.sql.Date, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row15) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row15<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Date, java.lang.Integer, java.sql.Date, java.lang.Integer> valuesRow() {
		return (org.jooq.Row15) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES.LOC_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES.LEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES.ID_LVL1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES.ID_LVL2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES.ID_LVL3;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES.ID_LVL4;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES.ID_LVL5;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES.ID_LVL6;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES.ID_LVL7;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES.ID_LVL8;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field11() {
		return DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES.ID_LVL9;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field12() {
		return DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES.VALID_SINCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field13() {
		return DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES.DATE_TYPE_SINCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field14() {
		return DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES.VALID_UNTIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field15() {
		return DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES.DATE_TYPE_UNTIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getLocId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getLevel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getIdLvl1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getIdLvl2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getIdLvl3();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getIdLvl4();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getIdLvl5();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getIdLvl6();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getIdLvl7();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getIdLvl8();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value11() {
		return getIdLvl9();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value12() {
		return getValidSince();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value13() {
		return getDateTypeSince();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value14() {
		return getValidUntil();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value15() {
		return getDateTypeUntil();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GeodbHierarchiesRecord
	 */
	public GeodbHierarchiesRecord() {
		super(DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES);
	}

	/**
	 * Create a detached, initialised GeodbHierarchiesRecord
	 */
	public GeodbHierarchiesRecord(java.lang.Integer locId, java.lang.Integer level, java.lang.Integer idLvl1, java.lang.Integer idLvl2, java.lang.Integer idLvl3, java.lang.Integer idLvl4, java.lang.Integer idLvl5, java.lang.Integer idLvl6, java.lang.Integer idLvl7, java.lang.Integer idLvl8, java.lang.Integer idLvl9, java.sql.Date validSince, java.lang.Integer dateTypeSince, java.sql.Date validUntil, java.lang.Integer dateTypeUntil) {
		super(DBAdapter.tables.GeodbHierarchies.GEODB_HIERARCHIES);

		setValue(0, locId);
		setValue(1, level);
		setValue(2, idLvl1);
		setValue(3, idLvl2);
		setValue(4, idLvl3);
		setValue(5, idLvl4);
		setValue(6, idLvl5);
		setValue(7, idLvl6);
		setValue(8, idLvl7);
		setValue(9, idLvl8);
		setValue(10, idLvl9);
		setValue(11, validSince);
		setValue(12, dateTypeSince);
		setValue(13, validUntil);
		setValue(14, dateTypeUntil);
	}
}
