/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeodbFloatdataRecord extends org.jooq.impl.TableRecordImpl<DBAdapter.tables.records.GeodbFloatdataRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.Integer, java.lang.Double, java.sql.Date, java.lang.Integer, java.sql.Date, java.lang.Integer> {

	private static final long serialVersionUID = -383822952;

	/**
	 * Setter for <code>MI_WS1314.geodb_floatdata.loc_id</code>. 
	 */
	public void setLocId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_floatdata.loc_id</code>. 
	 */
	public java.lang.Integer getLocId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_floatdata.float_type</code>. 
	 */
	public void setFloatType(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_floatdata.float_type</code>. 
	 */
	public java.lang.Integer getFloatType() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_floatdata.float_val</code>. 
	 */
	public void setFloatVal(java.lang.Double value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_floatdata.float_val</code>. 
	 */
	public java.lang.Double getFloatVal() {
		return (java.lang.Double) getValue(2);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_floatdata.valid_since</code>. 
	 */
	public void setValidSince(java.sql.Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_floatdata.valid_since</code>. 
	 */
	public java.sql.Date getValidSince() {
		return (java.sql.Date) getValue(3);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_floatdata.date_type_since</code>. 
	 */
	public void setDateTypeSince(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_floatdata.date_type_since</code>. 
	 */
	public java.lang.Integer getDateTypeSince() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_floatdata.valid_until</code>. 
	 */
	public void setValidUntil(java.sql.Date value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_floatdata.valid_until</code>. 
	 */
	public java.sql.Date getValidUntil() {
		return (java.sql.Date) getValue(5);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_floatdata.date_type_until</code>. 
	 */
	public void setDateTypeUntil(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_floatdata.date_type_until</code>. 
	 */
	public java.lang.Integer getDateTypeUntil() {
		return (java.lang.Integer) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.Double, java.sql.Date, java.lang.Integer, java.sql.Date, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.Double, java.sql.Date, java.lang.Integer, java.sql.Date, java.lang.Integer> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return DBAdapter.tables.GeodbFloatdata.GEODB_FLOATDATA.LOC_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return DBAdapter.tables.GeodbFloatdata.GEODB_FLOATDATA.FLOAT_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field3() {
		return DBAdapter.tables.GeodbFloatdata.GEODB_FLOATDATA.FLOAT_VAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field4() {
		return DBAdapter.tables.GeodbFloatdata.GEODB_FLOATDATA.VALID_SINCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return DBAdapter.tables.GeodbFloatdata.GEODB_FLOATDATA.DATE_TYPE_SINCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field6() {
		return DBAdapter.tables.GeodbFloatdata.GEODB_FLOATDATA.VALID_UNTIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return DBAdapter.tables.GeodbFloatdata.GEODB_FLOATDATA.DATE_TYPE_UNTIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getLocId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getFloatType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value3() {
		return getFloatVal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value4() {
		return getValidSince();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getDateTypeSince();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value6() {
		return getValidUntil();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getDateTypeUntil();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GeodbFloatdataRecord
	 */
	public GeodbFloatdataRecord() {
		super(DBAdapter.tables.GeodbFloatdata.GEODB_FLOATDATA);
	}

	/**
	 * Create a detached, initialised GeodbFloatdataRecord
	 */
	public GeodbFloatdataRecord(java.lang.Integer locId, java.lang.Integer floatType, java.lang.Double floatVal, java.sql.Date validSince, java.lang.Integer dateTypeSince, java.sql.Date validUntil, java.lang.Integer dateTypeUntil) {
		super(DBAdapter.tables.GeodbFloatdata.GEODB_FLOATDATA);

		setValue(0, locId);
		setValue(1, floatType);
		setValue(2, floatVal);
		setValue(3, validSince);
		setValue(4, dateTypeSince);
		setValue(5, validUntil);
		setValue(6, dateTypeUntil);
	}
}
