/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeodbTextdataRecord extends org.jooq.impl.TableRecordImpl<DBAdapter.tables.records.GeodbTextdataRecord> implements org.jooq.Record10<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Short, java.lang.Short, java.sql.Date, java.lang.Integer, java.sql.Date, java.lang.Integer> {

	private static final long serialVersionUID = -1192056912;

	/**
	 * Setter for <code>MI_WS1314.geodb_textdata.loc_id</code>. 
	 */
	public void setLocId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_textdata.loc_id</code>. 
	 */
	public java.lang.Integer getLocId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_textdata.text_type</code>. 
	 */
	public void setTextType(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_textdata.text_type</code>. 
	 */
	public java.lang.Integer getTextType() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_textdata.text_val</code>. 
	 */
	public void setTextVal(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_textdata.text_val</code>. 
	 */
	public java.lang.String getTextVal() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_textdata.text_locale</code>. 
	 */
	public void setTextLocale(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_textdata.text_locale</code>. 
	 */
	public java.lang.String getTextLocale() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_textdata.is_native_lang</code>. 
	 */
	public void setIsNativeLang(java.lang.Short value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_textdata.is_native_lang</code>. 
	 */
	public java.lang.Short getIsNativeLang() {
		return (java.lang.Short) getValue(4);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_textdata.is_default_name</code>. 
	 */
	public void setIsDefaultName(java.lang.Short value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_textdata.is_default_name</code>. 
	 */
	public java.lang.Short getIsDefaultName() {
		return (java.lang.Short) getValue(5);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_textdata.valid_since</code>. 
	 */
	public void setValidSince(java.sql.Date value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_textdata.valid_since</code>. 
	 */
	public java.sql.Date getValidSince() {
		return (java.sql.Date) getValue(6);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_textdata.date_type_since</code>. 
	 */
	public void setDateTypeSince(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_textdata.date_type_since</code>. 
	 */
	public java.lang.Integer getDateTypeSince() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_textdata.valid_until</code>. 
	 */
	public void setValidUntil(java.sql.Date value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_textdata.valid_until</code>. 
	 */
	public java.sql.Date getValidUntil() {
		return (java.sql.Date) getValue(8);
	}

	/**
	 * Setter for <code>MI_WS1314.geodb_textdata.date_type_until</code>. 
	 */
	public void setDateTypeUntil(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>MI_WS1314.geodb_textdata.date_type_until</code>. 
	 */
	public java.lang.Integer getDateTypeUntil() {
		return (java.lang.Integer) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Short, java.lang.Short, java.sql.Date, java.lang.Integer, java.sql.Date, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Short, java.lang.Short, java.sql.Date, java.lang.Integer, java.sql.Date, java.lang.Integer> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return DBAdapter.tables.GeodbTextdata.GEODB_TEXTDATA.LOC_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return DBAdapter.tables.GeodbTextdata.GEODB_TEXTDATA.TEXT_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return DBAdapter.tables.GeodbTextdata.GEODB_TEXTDATA.TEXT_VAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return DBAdapter.tables.GeodbTextdata.GEODB_TEXTDATA.TEXT_LOCALE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field5() {
		return DBAdapter.tables.GeodbTextdata.GEODB_TEXTDATA.IS_NATIVE_LANG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field6() {
		return DBAdapter.tables.GeodbTextdata.GEODB_TEXTDATA.IS_DEFAULT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field7() {
		return DBAdapter.tables.GeodbTextdata.GEODB_TEXTDATA.VALID_SINCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return DBAdapter.tables.GeodbTextdata.GEODB_TEXTDATA.DATE_TYPE_SINCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field9() {
		return DBAdapter.tables.GeodbTextdata.GEODB_TEXTDATA.VALID_UNTIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return DBAdapter.tables.GeodbTextdata.GEODB_TEXTDATA.DATE_TYPE_UNTIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getLocId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getTextType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getTextVal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getTextLocale();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value5() {
		return getIsNativeLang();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value6() {
		return getIsDefaultName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value7() {
		return getValidSince();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getDateTypeSince();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value9() {
		return getValidUntil();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getDateTypeUntil();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GeodbTextdataRecord
	 */
	public GeodbTextdataRecord() {
		super(DBAdapter.tables.GeodbTextdata.GEODB_TEXTDATA);
	}

	/**
	 * Create a detached, initialised GeodbTextdataRecord
	 */
	public GeodbTextdataRecord(java.lang.Integer locId, java.lang.Integer textType, java.lang.String textVal, java.lang.String textLocale, java.lang.Short isNativeLang, java.lang.Short isDefaultName, java.sql.Date validSince, java.lang.Integer dateTypeSince, java.sql.Date validUntil, java.lang.Integer dateTypeUntil) {
		super(DBAdapter.tables.GeodbTextdata.GEODB_TEXTDATA);

		setValue(0, locId);
		setValue(1, textType);
		setValue(2, textVal);
		setValue(3, textLocale);
		setValue(4, isNativeLang);
		setValue(5, isDefaultName);
		setValue(6, validSince);
		setValue(7, dateTypeSince);
		setValue(8, validUntil);
		setValue(9, dateTypeUntil);
	}
}
