/**
 * This class is generated by jOOQ
 */
package DBAdapter.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformationRecord extends org.jooq.impl.UpdatableRecordImpl<DBAdapter.tables.records.InformationRecord> implements org.jooq.Record3<java.lang.Long, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 186549375;

	/**
	 * Setter for <code>MI_WS1314.information.tweet_id</code>. 
	 */
	public void setTweetId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>MI_WS1314.information.tweet_id</code>. 
	 */
	public java.lang.Long getTweetId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>MI_WS1314.information.geolocation</code>. 
	 */
	public void setGeolocation(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>MI_WS1314.information.geolocation</code>. 
	 */
	public java.lang.String getGeolocation() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>MI_WS1314.information.place</code>. 
	 */
	public void setPlace(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>MI_WS1314.information.place</code>. 
	 */
	public java.lang.String getPlace() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return DBAdapter.tables.Information.INFORMATION.TWEET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return DBAdapter.tables.Information.INFORMATION.GEOLOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return DBAdapter.tables.Information.INFORMATION.PLACE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getTweetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getGeolocation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getPlace();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached InformationRecord
	 */
	public InformationRecord() {
		super(DBAdapter.tables.Information.INFORMATION);
	}

	/**
	 * Create a detached, initialised InformationRecord
	 */
	public InformationRecord(java.lang.Long tweetId, java.lang.String geolocation, java.lang.String place) {
		super(DBAdapter.tables.Information.INFORMATION);

		setValue(0, tweetId);
		setValue(1, geolocation);
		setValue(2, place);
	}
}
